### ISSUE TITLE
No releases available for package "pecl.php.net/xdebug"

### ISSUE THREAD

**Issue by MarcelRobitaille** [christianlupus/nextcloud-docker-debug#8]
Thanks for creating this development environment, which used to be working for me. However, today I got errors when doing `docker-compose up` and tried doing `docker-compose build --pull` again. I tried deleting the repository and cloning again, but I am getting this error:

```
db uses an image, skipping
redis uses an image, skipping
Building app
Sending build context to Docker daemon   7.68kB
Step 1/10 : FROM nextcloud:apache
apache: Pulling from library/nextcloud
Digest: sha256:ad72af6ae69164512c4da88a05631454d969bb9170f4af1cab0c4bf696abcc52
Status: Image is up to date for nextcloud:apache
 ---> cc45052d6b45
Step 2/10 : RUN pecl install xdebug && docker-php-ext-enable xdebug
 ---> Running in 448217bc29dd
No releases available for package "pecl.php.net/xdebug"
install failed
The command '/bin/sh -c pecl install xdebug && docker-php-ext-enable xdebug' returned a non-zero code: 1
ERROR: Service 'app' failed to build : Build failed
```

I read it could be a networking error, but I get the same thing with and without my VPN and I am not using a network proxy. I wonder if it's because the image versions may have drifted.

**Comment by christianlupus** [comment]
I just pushed a patch [c1cc90a](https://github.com/christianlupus/nextcloud-docker-debug/commit/c1cc90abc8aa9ad18150e8ac99e08dd1d339e518) to the repo.

Could you please try again, @MarcelRobitaille?

**Comment by MarcelRobitaille** [comment]
Thanks for the patch. I'm still getting a similar error. Looks like it could be a DNS issue though. I've had problems before with DNS inside docker.

I followed [this](https://serverfault.com/questions/642981/docker-containers-cant-resolve-dns-on-ubuntu-14-04-desktop-host) and it seems to be fixed.

```
db uses an image, skipping
redis uses an image, skipping
Building app
Sending build context to Docker daemon   7.68kB
Step 1/10 : FROM nextcloud:apache
apache: Pulling from library/nextcloud
Digest: sha256:ad72af6ae69164512c4da88a05631454d969bb9170f4af1cab0c4bf696abcc52
Status: Image is up to date for nextcloud:apache
 ---> cc45052d6b45
Step 2/10 : RUN         pecl update-channels &&         pecl install xdebug && docker-php-ext-enable xdebug
 ---> Running in 6e2f54c274ac
Updating channel "doc.php.net"
Channel "doc.php.net" is not responding over http://, failed with message: Connection to `doc.php.net:80' failed: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution
Trying channel "doc.php.net" over https:// instead
Cannot retrieve channel.xml for channel "doc.php.net" (Connection to `ssl://doc.php.net:443' failed: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution)
Updating channel "pear.php.net"
Channel "pear.php.net" is not responding over http://, failed with message: Connection to `pear.php.net:80' failed: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution
Trying channel "pear.php.net" over https:// instead
Cannot retrieve channel.xml for channel "pear.php.net" (Connection to `ssl://pear.php.net:443' failed: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution)
Updating channel "pecl.php.net"
Channel "pecl.php.net" is not responding over http://, failed with message: Connection to `pecl.php.net:80' failed: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution
Trying channel "pecl.php.net" over https:// instead
Cannot retrieve channel.xml for channel "pecl.php.net" (Connection to `ssl://pecl.php.net:443' failed: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution)
No releases available for package "pecl.php.net/xdebug"
install failed
The command '/bin/sh -c pecl update-channels &&         pecl install xdebug && docker-php-ext-enable xdebug' returned a non-zero code: 1
ERROR: Service 'app' failed to build : Build failed
```
